# Generated by Django 6.0.3 on 2026-05-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='is_stil_on_site',
            new_name='is_still_on_site',
        ),
    ]
