# Generated by Django 6.0.3 on 2026-06-10 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_rename_is_stil_on_site_visitor_is_still_on_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_full_name', models.CharField(max_length=150)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_company', models.CharField(blank=True, max_length=150)),
                ('planned_arrival', models.DateTimeField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('purpose_of_visit', models.TextField(blank=True)),
                ('safety_instructions_signed', models.BooleanField(default=False)),
                ('nda_accepted', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planned_arrival'],
            },
        ),
    ]
