# Generated by Django 6.0.3 on 2026-07-10 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visitor_company',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visitor_email',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visitor_full_name',
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_visits', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
